### ISSUE TITLE
Improve Feature Search

### ISSUE THREAD

**Issue by yuliakbard** [mecha-cms/bounty#4]
di mecha cms ekstensi search biasanya route search nya itu biasanya di routing ke dalam folder article (default) atau di custom lewat route-blog. ane mau route search nya itu ada di route /search tapi bisa nampilin semua hasil pencarian di semua folder utama. apakah memungkinkan kang?

**Comment by taufik-nurrohman** [comment]
Coba cek versi 2.1.0 mas :+1: Kalau sudah oke, isu ini bisa ditutup. Diskusi mengenai fitur dan konfigurasi bisa dilakukan seperti biasa di [Diskusi](https://github.com/mecha-cms/mecha/discussions).
