### ISSUE TITLE
Request Feed Feature for User Data

### ISSUE THREAD

**Issue by yuliakbard** [mecha-cms/bounty#5]
### Describe your feature request in the field below

saya ingin mengambil data dari feed.json pada folder user

### Provide financial support (USD)

5

### Have money to donate?

- [X] I will donate my money as written above once the feature is available.

**Comment by taufik-nurrohman** [comment]
Kemungkinannya begini mas:

Rute | Tugas
---- | -----
`/user/feed.json` | Menampilkan daftar pengguna.
~~`/user/feed.json?name=taufik-nurrohman`~~ | ~~Menampilkan informasi pengguna `@taufik-nurrohman`~~
`/user/taufik-nurrohman/feed.json` | Menampilkan informasi pengguna `@taufik-nurrohman`

**Comment by taufik-nurrohman** [comment]
Mohon berikan masukan sebelum versi 1.0.0 dirilis: <https://github.com/mecha-cms/x.feed.user>

**Comment by yuliakbard** [comment]
Cara rute 1

`/user/feed.json`

![image](https://github.com/user-attachments/assets/c548f723-fa4f-4bf5-a261-80eb799ac7f7)

Cara rute 2

`/user/feed.json?name=yuliakbard`

![image](https://github.com/user-attachments/assets/f66b43f9-3056-40c4-886f-055f7d15149d)
belum sesuai resultnya.


Cara rute 3

`/user/yuliakbard/feed.json`

![image](https://github.com/user-attachments/assets/a137dc37-2893-4ab1-9800-21e47d884a5e)

**Comment by yuliakbard** [comment]
untuk yg null itu, biar tampil gimana ya kang? itu tarik data yg mana ya kang? kalau misal  title dan description itu ambil dari menu state, harusnya muncul nama website dan description nya

**Comment by taufik-nurrohman** [comment]
Yang cara rute 2 sudah saya batalkan.

Untuk judul dan deskripsi masih tak kosongi. Kira-kira penting apa tidak sih mas? Sepertinya kok enggak terpakai ya?
